version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: code_review_backend
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./data:/app/data
      - ./faiss_indexes:/app/faiss_indexes
      - ./db.sqlite:/app/db.sqlite
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: code_review_redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: code_review_worker
    depends_on:
      - backend
      - redis
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./data:/app/data
      - ./faiss_indexes:/app/faiss_indexes
      - ./db.sqlite:/app/db.sqlite

  # Optional: Dashboard service
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dashboard
    container_name: code_review_dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend
